// Цвета
export const C = {
  bg:        '#08090b',
  bgCard:    '#0a0b0f',
  bgInput:   '#0a0c10',
  bgHover:   '#ffffff08',
  border:    '#1a1c22',
  borderMid: '#2a2d35',
  text:      '#c8cdd6',
  textDim:   '#606570',
  textFaint: '#404550',
  textBright:'#e8ecf4',
};

// Общие стили для input/select/textarea
export const S = {
  input: {
    background: C.bgInput,
    border: `1px solid ${C.borderMid}`,
    borderRadius: 4,
    padding: '5px 8px',
    color: C.text,
    fontSize: 11,
    outline: 'none',
    fontFamily: 'JetBrains Mono',
    width: '100%',
    boxSizing: 'border-box',
  },
  select: {
    background: C.bgInput,
    border: `1px solid ${C.borderMid}`,
    borderRadius: 4,
    padding: '5px 7px',
    color: C.text,
    fontSize: 11,
    outline: 'none',
    fontFamily: 'JetBrains Mono',
    width: '100%',
    boxSizing: 'border-box',
  },
  textarea: {
    background: C.bgInput,
    border: `1px solid ${C.borderMid}`,
    borderRadius: 4,
    padding: '6px 8px',
    color: C.text,
    fontSize: 11,
    outline: 'none',
    fontFamily: 'JetBrains Mono',
    width: '100%',
    resize: 'vertical',
    boxSizing: 'border-box',
  },
  card: {
    background: C.bgCard,
    border: `1px solid ${C.border}`,
    borderRadius: 6,
  },
  badge: (color) => ({
    display: 'inline-flex',
    alignItems: 'center',
    padding: '2px 7px',
    borderRadius: 10,
    fontSize: 10,
    fontWeight: 600,
    background: `${color}22`,
    color: color,
    border: `1px solid ${color}44`,
    fontFamily: 'JetBrains Mono',
    whiteSpace: 'nowrap',
  }),
};
