#!/usr/bin/env bash
# Generates a .env file with secure random secrets.
# Run once before first launch: bash scripts/gen_env.sh
set -euo pipefail

ENV_FILE="$(dirname "$0")/../.env"

if [ -f "$ENV_FILE" ]; then
  echo "ERROR: .env already exists. Remove it first if you want to regenerate."
  exit 1
fi

JWT_SECRET=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)
ENCRYPTION_KEY=$(openssl rand -base64 32 | tr '+/' '-_' | tr -d '=')

cat > "$ENV_FILE" <<EOF
# Generated by scripts/gen_env.sh — keep this file secret, never commit it.

DB_USER=rtnotes
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=rtnotes

JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

ADMIN_USERNAME=admin
ADMIN_PASSWORD=$(openssl rand -hex 8)

PORT=3000

COOKIE_SECURE=false
CORS_ORIGINS=
EOF

echo "Created .env with secure random secrets."
echo "ADMIN_PASSWORD is set — check .env before first login."
